services:
  mgmt_frontend:
    depends_on:
    - redis
    image: clipper/management_frontend:latest
    labels:
      - "ai.clipper.container.label"
    command:
    - "--redis_ip=redis"
    - "--redis_port=6379"
    ports:
    - 1338:1338
    restart: always
  redis:
    image: redis:alpine
    labels:
      - "ai.clipper.container.label"
    command: redis-server --port 6379
    ports:
    - 6379:6379
    restart: always
    volumes:
      - redisdata:/data
  query_frontend:
    depends_on:
    - mgmt_frontend
    - redis
    image: clipper/query_frontend:latest
    labels:
      - "ai.clipper.container.label"
    command:
    - "--redis_ip=redis"
    - "--redis_port=6379"
    ports:
    - 7000:7000
    - 1337:1337
    restart: always
version: '2'
networks:
  default:
    external:
      name: clipper_nw
volumes:
  redisdata:
